export interface SeedContest {
  title: string;
  category: "contest" | "hackathon" | "startup" | "grant";
  organizer: string;
  applicationStart: Date;
  applicationEnd: Date;
  field: string[];
  target: string[];
  region: string;
  summary: string;
  prize: string;
  eligibility: string;
  applyUrl: string;
  sourceUrl: string;
  checklist: string[];
  isActive: boolean;
}

export const SEED_DATA: SeedContest[] = [
  // ─────────────────────────────────────────
  // contest (공모전) × 6
  // ─────────────────────────────────────────
  {
    title: "2026 공공데이터 활용 창작 공모전",
    category: "contest",
    organizer: "행정안전부",
    applicationStart: new Date("2026-03-10"),
    applicationEnd: new Date("2026-05-09"),
    field: ["데이터", "AI", "소프트웨어"],
    target: ["대학생", "일반인", "개인"],
    region: "전국",
    summary:
      "공공데이터포털의 데이터를 활용하여 사회 문제를 해결하는 서비스·앱·시각화 작품을 공모합니다.",
    prize: "총 5,000만원 (대상 1,500만원)",
    eligibility: "대한민국 국민 누구나 (팀 최대 5인)",
    applyUrl: "https://example.com/apply/1",
    sourceUrl: "https://example.com/source/1",
    checklist: [
      "참가신청서",
      "작품설명서(A4 5매 이내)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "제12회 대한민국 청년 사회혁신 아이디어 공모전",
    category: "contest",
    organizer: "한국사회혁신진흥원",
    applicationStart: new Date("2026-04-01"),
    applicationEnd: new Date("2026-05-31"),
    field: ["사회혁신", "환경", "복지"],
    target: ["대학생", "청년(만 19-39세)"],
    region: "전국",
    summary:
      "사회적 가치를 창출하는 혁신 아이디어를 발굴하고 지원하는 공모전입니다. 환경·복지·교육 분야 우선.",
    prize: "총 3,000만원 (최우수 800만원)",
    eligibility: "만 19세~39세 청년 (개인 또는 팀 최대 3인)",
    applyUrl: "https://example.com/apply/2",
    sourceUrl: "https://example.com/source/2",
    checklist: [
      "아이디어 제안서",
      "팀 구성원 소개서",
      "개인정보 수집·이용 동의서",
      "청년 연령 증빙서류",
    ],
    isActive: true,
  },
  {
    title: "2026 K-디자인 어워드 학생 부문",
    category: "contest",
    organizer: "한국디자인진흥원(KIDP)",
    applicationStart: new Date("2026-03-15"),
    applicationEnd: new Date("2026-06-14"),
    field: ["디자인", "UX/UI", "제품디자인"],
    target: ["대학생", "대학원생"],
    region: "전국",
    summary:
      "국내 대학(원)생을 대상으로 한 디자인 역량 발굴 공모전. 시각·제품·공간·UX 4개 트랙 운영.",
    prize: "총 2,500만원 (각 트랙 대상 300만원)",
    eligibility: "국내 4년제 또는 전문대학 재학·휴학생",
    applyUrl: "https://example.com/apply/3",
    sourceUrl: "https://example.com/source/3",
    checklist: [
      "작품 포트폴리오(PDF)",
      "재학증명서",
      "지도교수 확인서(선택)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 AI 콘텐츠 크리에이터 공모전",
    category: "contest",
    organizer: "과학기술정보통신부·NIA",
    applicationStart: new Date("2026-05-01"),
    applicationEnd: new Date("2026-06-30"),
    field: ["AI", "콘텐츠", "미디어"],
    target: ["대학생", "일반인", "크리에이터"],
    region: "온라인",
    summary:
      "생성형 AI 도구를 활용하여 영상·이미지·텍스트 콘텐츠를 제작하는 공모전. 창의성과 기술 활용도 평가.",
    prize: "총 4,000만원 (대상 1,000만원)",
    eligibility: "대한민국 국민 누구나",
    applyUrl: "https://example.com/apply/4",
    sourceUrl: "https://example.com/source/4",
    checklist: [
      "작품 파일(영상/이미지)",
      "제작 과정 설명서",
      "사용 AI 도구 명시",
      "저작권 확인서",
    ],
    isActive: true,
  },
  {
    title: "부산 스마트시티 아이디어 공모전 2026",
    category: "contest",
    organizer: "부산광역시·부산테크노파크",
    applicationStart: new Date("2026-04-15"),
    applicationEnd: new Date("2026-07-14"),
    field: ["스마트시티", "IoT", "교통", "환경"],
    target: ["대학생", "일반인", "스타트업"],
    region: "부산",
    summary:
      "부산의 도시 문제를 ICT 기술로 해결하는 아이디어 공모. 교통·환경·안전·생활편의 분야 중심.",
    prize: "총 3,500만원 (최우수 1,000만원)",
    eligibility: "부산시민 또는 부산 소재 기업·대학 구성원",
    applyUrl: "https://example.com/apply/5",
    sourceUrl: "https://example.com/source/5",
    checklist: [
      "아이디어 기획서(10매 이내)",
      "시연 영상(3분 이내)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "제7회 핀테크 아이디어 공모전",
    category: "contest",
    organizer: "금융위원회·코스콤",
    applicationStart: new Date("2026-06-01"),
    applicationEnd: new Date("2026-07-31"),
    field: ["핀테크", "금융", "AI", "블록체인"],
    target: ["대학생", "대학원생", "일반인"],
    region: "전국",
    summary:
      "금융 서비스 혁신을 위한 핀테크 아이디어를 공모합니다. 실현 가능성과 비즈니스 모델 구체성 중점 평가.",
    prize: "총 6,000만원 (대상 2,000만원)",
    eligibility: "대한민국 국민 누구나 (팀 최대 4인)",
    applyUrl: "https://example.com/apply/6",
    sourceUrl: "https://example.com/source/6",
    checklist: [
      "사업계획서",
      "프로토타입 또는 목업",
      "팀 소개서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },

  // ─────────────────────────────────────────
  // hackathon (해커톤) × 6
  // ─────────────────────────────────────────
  {
    title: "NAVER AI 해커톤 2026",
    category: "hackathon",
    organizer: "네이버(NAVER)",
    applicationStart: new Date("2026-03-20"),
    applicationEnd: new Date("2026-04-20"),
    field: ["AI", "자연어처리", "검색", "추천"],
    target: ["대학생", "대학원생", "개발자"],
    region: "경기 성남(판교)",
    summary:
      "네이버 AI 플랫폼 HyperCLOVA X를 활용한 서비스 개발 해커톤. 48시간 집중 개발 후 현장 발표.",
    prize: "총 5,000만원 (우승 2,000만원 + 인턴십 기회)",
    eligibility: "개발자 누구나 (팀 3~5인, 대학생 팀 우대)",
    applyUrl: "https://example.com/apply/7",
    sourceUrl: "https://example.com/source/7",
    checklist: [
      "팀 등록서",
      "아이디어 요약서(500자)",
      "깃허브 프로필 링크",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 카카오 소셜임팩트 해커톤",
    category: "hackathon",
    organizer: "카카오임팩트",
    applicationStart: new Date("2026-04-10"),
    applicationEnd: new Date("2026-05-10"),
    field: ["사회혁신", "AI", "모바일", "접근성"],
    target: ["대학생", "개발자", "디자이너", "기획자"],
    region: "서울",
    summary:
      "사회 문제를 기술로 해결하는 2박 3일 해커톤. 개발·디자인·기획 직군 혼합 팀 구성 필수.",
    prize: "총 2,000만원 (대상 800만원 + 카카오 채용 연계)",
    eligibility: "직군 혼합 팀 3~5인 (개발 필수 1인 이상)",
    applyUrl: "https://example.com/apply/8",
    sourceUrl: "https://example.com/source/8",
    checklist: ["팀 구성 계획서", "문제 정의서", "개인정보 수집·이용 동의서"],
    isActive: true,
  },
  {
    title: "보건복지부 디지털 헬스케어 해커톤",
    category: "hackathon",
    organizer: "보건복지부·한국보건산업진흥원",
    applicationStart: new Date("2026-05-15"),
    applicationEnd: new Date("2026-06-15"),
    field: ["헬스케어", "AI", "의료", "웨어러블"],
    target: ["대학생", "개발자", "의료인"],
    region: "대전",
    summary:
      "디지털 헬스케어 분야 스타트업 발굴을 위한 해커톤. 의료진과 개발자가 협업하는 팀 구성 장려.",
    prize: "총 4,500만원 (최우수 1,500만원)",
    eligibility: "팀 2~5인 (의료 또는 IT 분야 전문성 보유)",
    applyUrl: "https://example.com/apply/9",
    sourceUrl: "https://example.com/source/9",
    checklist: [
      "팀 구성 계획서",
      "솔루션 기획서",
      "개인정보 수집·이용 동의서",
      "전문성 증빙 자료",
    ],
    isActive: true,
  },
  {
    title: "Seoul Open Data Hackathon 2026",
    category: "hackathon",
    organizer: "서울특별시",
    applicationStart: new Date("2026-05-20"),
    applicationEnd: new Date("2026-06-20"),
    field: ["데이터", "스마트시티", "공공서비스"],
    target: ["대학생", "개발자", "일반인"],
    region: "서울",
    summary:
      "서울 열린데이터광장 공개 데이터를 활용해 시민 생활 편의를 높이는 앱·서비스를 24시간 안에 개발.",
    prize: "총 3,000만원 (1등 1,000만원)",
    eligibility: "누구나 (팀 2~4인)",
    applyUrl: "https://example.com/apply/10",
    sourceUrl: "https://example.com/source/10",
    checklist: [
      "사전 등록서",
      "프로젝트 아이디어 요약(300자)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 그린테크 기후변화 해커톤",
    category: "hackathon",
    organizer: "환경부·한국환경산업기술원",
    applicationStart: new Date("2026-06-10"),
    applicationEnd: new Date("2026-07-10"),
    field: ["환경", "그린테크", "에너지", "AI"],
    target: ["대학생", "스타트업", "개발자"],
    region: "온라인",
    summary:
      "탄소중립 달성을 위한 기술 솔루션을 개발하는 온라인 해커톤. 에너지 절감·탄소추적·친환경 모빌리티 트랙.",
    prize: "총 3,500만원 (각 트랙 우승 500만원)",
    eligibility: "국내외 참가 가능 (팀 2~5인)",
    applyUrl: "https://example.com/apply/11",
    sourceUrl: "https://example.com/source/11",
    checklist: [
      "팀 등록서",
      "트랙 선택 및 아이디어 개요",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "대전 스타트업 위크엔드 2026",
    category: "hackathon",
    organizer: "Techstars·대전창조경제혁신센터",
    applicationStart: new Date("2026-07-01"),
    applicationEnd: new Date("2026-08-01"),
    field: ["창업", "소프트웨어", "비즈니스모델"],
    target: ["예비창업자", "대학생", "직장인"],
    region: "대전",
    summary:
      "54시간 동안 아이디어를 실제 스타트업으로 만들어가는 글로벌 해커톤 프로그램. 멘토링·네트워킹 포함.",
    prize: "우승팀 액셀러레이팅 프로그램 참여권 + 시드 투자 검토",
    eligibility: "누구나 (팀 또는 개인 참가 후 현장 팀 빌딩)",
    applyUrl: "https://example.com/apply/12",
    sourceUrl: "https://example.com/source/12",
    checklist: [
      "사전 등록서",
      "개인 소개서(선택)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },

  // ─────────────────────────────────────────
  // startup (예창패 / 창업 프로그램) × 6
  // ─────────────────────────────────────────
  {
    title: "2026년 예비창업패키지 (일반형)",
    category: "startup",
    organizer: "중소벤처기업부·창업진흥원",
    applicationStart: new Date("2026-02-03"),
    applicationEnd: new Date("2026-04-04"),
    field: ["창업", "전 분야"],
    target: ["예비창업자"],
    region: "전국",
    summary:
      "창업 아이디어를 보유한 예비창업자에게 최대 1억원 사업화 자금 및 멘토링을 지원하는 정부 대표 창업 프로그램.",
    prize: "최대 1억원 (평균 6,000만원)",
    eligibility: "사업자등록 전인 예비창업자 (전담기관별 특화 분야 상이)",
    applyUrl: "https://example.com/apply/13",
    sourceUrl: "https://example.com/source/13",
    checklist: [
      "사업계획서",
      "대표자 신분증",
      "개인정보 수집·이용 동의서",
      "창업 아이템 관련 자료",
    ],
    isActive: true,
  },
  {
    title: "초기창업패키지 2026 (딥테크 트랙)",
    category: "startup",
    organizer: "중소벤처기업부·창업진흥원",
    applicationStart: new Date("2026-03-01"),
    applicationEnd: new Date("2026-04-30"),
    field: ["딥테크", "AI", "바이오", "반도체"],
    target: ["초기 스타트업(창업 3년 이내)"],
    region: "전국",
    summary:
      "딥테크 분야 초기 스타트업의 기술 사업화를 지원. 최대 1억원 지원 및 전문 보육 기관 연계.",
    prize: "최대 1억원",
    eligibility: "창업 후 3년 이내 중소기업 (법인 또는 개인사업자)",
    applyUrl: "https://example.com/apply/14",
    sourceUrl: "https://example.com/source/14",
    checklist: [
      "사업계획서",
      "사업자등록증",
      "재무제표(해당 시)",
      "기술 관련 증빙자료",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "TIPS 프로그램 2026 상반기 모집",
    category: "startup",
    organizer: "중소벤처기업부·민간 투자사",
    applicationStart: new Date("2026-03-10"),
    applicationEnd: new Date("2026-05-09"),
    field: ["딥테크", "AI", "바이오", "소프트웨어"],
    target: ["스타트업(창업 7년 이내)"],
    region: "전국",
    summary:
      "민간 투자사 추천을 통해 선발된 스타트업에 정부 R&D 자금 최대 5억원을 지원하는 엔젤투자 매칭 프로그램.",
    prize: "R&D 자금 최대 5억원 + 해외마케팅·창업사업화 추가 지원",
    eligibility: "창업 7년 이내 기술창업기업 (TIPS 운영사 추천 필수)",
    applyUrl: "https://example.com/apply/15",
    sourceUrl: "https://example.com/source/15",
    checklist: [
      "사업계획서",
      "투자사 추천서",
      "사업자등록증",
      "기술개발 계획서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "서울창업허브 글로벌 액셀러레이팅 2026",
    category: "startup",
    organizer: "서울경제진흥원(SBA)",
    applicationStart: new Date("2026-04-01"),
    applicationEnd: new Date("2026-05-31"),
    field: ["글로벌 진출", "AI", "SaaS", "이커머스"],
    target: ["스타트업(창업 5년 이내)"],
    region: "서울",
    summary:
      "해외 진출을 목표로 하는 서울 소재 스타트업을 선발해 글로벌 멘토링·IR·마케팅비 최대 3,000만원 지원.",
    prize: "사업화 지원금 최대 3,000만원 + 글로벌 PoC 연계",
    eligibility: "서울 소재 또는 서울 이전 예정 스타트업",
    applyUrl: "https://example.com/apply/16",
    sourceUrl: "https://example.com/source/16",
    checklist: [
      "사업계획서(영문 포함)",
      "사업자등록증",
      "서비스/제품 소개 자료",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "여성창업 패키지 2026",
    category: "startup",
    organizer: "중소벤처기업부·여성기업종합지원센터",
    applicationStart: new Date("2026-05-01"),
    applicationEnd: new Date("2026-06-30"),
    field: ["창업", "전 분야", "소셜벤처"],
    target: ["여성 예비창업자", "여성 초기창업자"],
    region: "전국",
    summary:
      "여성 창업자를 위한 전용 창업 지원 프로그램. 사업화 자금 최대 7,000만원 및 맞춤형 멘토링 제공.",
    prize: "최대 7,000만원",
    eligibility: "여성 예비창업자 및 창업 3년 이내 여성 대표 기업",
    applyUrl: "https://example.com/apply/17",
    sourceUrl: "https://example.com/source/17",
    checklist: [
      "사업계획서",
      "대표자 신분증(여성 확인)",
      "개인정보 수집·이용 동의서",
      "창업 관련 자격증(선택)",
    ],
    isActive: true,
  },
  {
    title: "대학창업펀드 2026 (학생 창업)",
    category: "startup",
    organizer: "교육부·한국연구재단",
    applicationStart: new Date("2026-06-15"),
    applicationEnd: new Date("2026-07-31"),
    field: ["창업", "기술사업화", "AI", "바이오"],
    target: ["재학생 창업자", "졸업 3년 이내 청년"],
    region: "전국",
    summary:
      "대학 재학(원)생의 창업 도전을 지원하는 학생 창업 특화 프로그램. 사업화 자금 최대 5,000만원 지원.",
    prize: "최대 5,000만원",
    eligibility: "대학(원) 재학생 또는 졸업 3년 이내 (팀원 과반 이상 재학생)",
    applyUrl: "https://example.com/apply/18",
    sourceUrl: "https://example.com/source/18",
    checklist: [
      "사업계획서",
      "재학증명서 또는 졸업증명서",
      "사업자등록증(해당 시)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },

  // ─────────────────────────────────────────
  // grant (지원금 / 보조금) × 6
  // ─────────────────────────────────────────
  {
    title: "중소기업 AI 도입 바우처 2026",
    category: "grant",
    organizer: "중소벤처기업부·중소기업기술정보진흥원",
    applicationStart: new Date("2026-03-03"),
    applicationEnd: new Date("2026-04-25"),
    field: ["AI", "디지털전환", "제조", "서비스"],
    target: ["중소기업", "소상공인"],
    region: "전국",
    summary:
      "AI 솔루션 도입을 원하는 중소기업에 최대 3,000만원(자부담 30%) 바우처 지원. 수요기업-공급기업 매칭.",
    prize: "최대 3,000만원 (자부담 30%)",
    eligibility: "중소기업기본법상 중소기업 (제조·서비스업)",
    applyUrl: "https://example.com/apply/19",
    sourceUrl: "https://example.com/source/19",
    checklist: [
      "사업계획서",
      "사업자등록증",
      "재무제표(최근 1년)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "청년 디지털 창작자 지원사업 2026",
    category: "grant",
    organizer: "문화체육관광부·한국콘텐츠진흥원",
    applicationStart: new Date("2026-04-07"),
    applicationEnd: new Date("2026-05-23"),
    field: ["콘텐츠", "미디어", "웹툰", "유튜브"],
    target: ["청년 크리에이터(만 19-39세)"],
    region: "전국",
    summary:
      "유튜브·웹툰·팟캐스트 등 디지털 콘텐츠를 제작하는 청년 창작자에게 제작비·장비비 최대 500만원 지원.",
    prize: "최대 500만원 (제작비·장비비)",
    eligibility: "만 19~39세 청년, 채널 구독자 1,000명 이상(또는 동등 실적)",
    applyUrl: "https://example.com/apply/20",
    sourceUrl: "https://example.com/source/20",
    checklist: [
      "활동 포트폴리오",
      "지원금 사용 계획서",
      "채널 현황 캡처",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "소상공인 스마트상점 기술보급 사업 2026",
    category: "grant",
    organizer: "중소벤처기업부·소상공인시장진흥공단",
    applicationStart: new Date("2026-04-20"),
    applicationEnd: new Date("2026-06-06"),
    field: ["스마트기술", "유통", "소상공인"],
    target: ["소상공인"],
    region: "전국",
    summary:
      "키오스크·서빙로봇·스마트POS 등 스마트 기술을 소상공인 점포에 도입하는 비용의 70~80%를 보조.",
    prize: "최대 2,000만원 (자부담 20~30%)",
    eligibility: "소상공인기본법상 소상공인 (사업자등록 후 6개월 이상)",
    applyUrl: "https://example.com/apply/21",
    sourceUrl: "https://example.com/source/21",
    checklist: [
      "사업자등록증",
      "최근 부가세 과세표준 증명",
      "도입기술 견적서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "K-스타트업 글로벌 마케팅 지원사업",
    category: "grant",
    organizer: "KOTRA·중소벤처기업부",
    applicationStart: new Date("2026-05-12"),
    applicationEnd: new Date("2026-06-27"),
    field: ["글로벌 마케팅", "수출", "B2B", "SaaS"],
    target: ["스타트업", "중소기업"],
    region: "전국",
    summary:
      "해외 전시회 참가·현지 마케팅·바이어 발굴 비용을 지원하여 스타트업의 글로벌 진출을 가속화.",
    prize: "최대 5,000만원 (해외 마케팅비 70% 매칭)",
    eligibility: "수출 실적 보유 또는 수출 의지가 있는 창업 7년 이내 기업",
    applyUrl: "https://example.com/apply/22",
    sourceUrl: "https://example.com/source/22",
    checklist: [
      "사업계획서(글로벌 전략 포함)",
      "사업자등록증",
      "수출 실적 증빙(해당 시)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "지역주도형 청년 일자리 사업 2026",
    category: "grant",
    organizer: "행정안전부·각 광역지자체",
    applicationStart: new Date("2026-06-02"),
    applicationEnd: new Date("2026-07-18"),
    field: ["일자리", "지역균형발전", "창업"],
    target: ["청년(만 18-39세)", "비수도권 거주 또는 이주 희망자"],
    region: "비수도권 전 지역",
    summary:
      "비수도권 지역 기업·기관에 취업하거나 창업하는 청년에게 인건비·정착비 최대 2년간 지원.",
    prize: "월 최대 180만원 × 최대 24개월",
    eligibility: "만 18~39세 청년, 비수도권 지역 사업체 취·창업",
    applyUrl: "https://example.com/apply/23",
    sourceUrl: "https://example.com/source/23",
    checklist: [
      "취업(창업) 확인서",
      "주민등록등본",
      "청년 연령 증빙",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 R&D 바우처 (중견기업 혁신형)",
    category: "grant",
    organizer: "산업통상자원부·한국산업기술진흥원(KIAT)",
    applicationStart: new Date("2026-07-01"),
    applicationEnd: new Date("2026-08-29"),
    field: ["R&D", "제조혁신", "AI", "소재·부품"],
    target: ["중견기업", "강소기업"],
    region: "전국",
    summary:
      "혁신 역량을 갖춘 중견기업이 연구기관·대학과 공동 R&D를 수행할 수 있도록 바우처 형태로 최대 2억원 지원.",
    prize: "최대 2억원 (자부담 40%)",
    eligibility: "중견기업법상 중견기업 또는 강소기업 인증 보유 기업",
    applyUrl: "https://example.com/apply/24",
    sourceUrl: "https://example.com/source/24",
    checklist: [
      "사업계획서",
      "사업자등록증",
      "재무제표(최근 2년)",
      "R&D 과제 계획서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
];
