export interface SeedContest {
  title: string;
  category: "contest" | "hackathon" | "startup" | "grant";
  organizer: string;
  applicationStart: Date;
  applicationEnd: Date;
  field: string[];
  target: string[];
  region: string;
  summary: string;
  prize: string;
  eligibility: string;
  applyUrl: string;
  sourceUrl: string;
  checklist: string[];
  isActive: boolean;
}

export const SEED_DATA: SeedContest[] = [
  // ─────────────────────────────────────────
  // contest (공모전) × 12
  // ─────────────────────────────────────────
  {
    title: "2026년 전국 통합데이터 활용 공모전",
    category: "contest",
    organizer: "행정안전부·한국지역정보개발원",
    applicationStart: new Date("2026-03-30"),
    applicationEnd: new Date("2026-04-25"),
    field: ["데이터", "소프트웨어", "AI", "공공서비스"],
    target: ["대학생", "일반인", "스타트업"],
    region: "전국",
    summary:
      "전국 통합개방데이터(공영자전거·버스 실시간 정보·교통약자 이동지원 등 7종)를 1종 이상 활용한 웹·앱 서비스를 공모합니다. 총 상금 1,400만원.",
    prize:
      "총 1,400만원 (대상 400만원, 최우수상 300만원, 우수상 3건 각 150만원)",
    eligibility: "대한민국 국민 누구나 (개인 또는 팀)",
    applyUrl:
      "https://sotong.go.kr/front/epilogue/epilogueNewViewPage.do?bbs_id=6f883cdbbf0747a5b08455f9804943ec",
    sourceUrl: "https://linkareer.com/activity/311947",
    checklist: [
      "서비스 개발 결과물(웹 또는 앱)",
      "활용 데이터 출처 명시",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 청년 AI 디자인 공모전 (서초구)",
    category: "contest",
    organizer: "서초구",
    applicationStart: new Date("2026-03-03"),
    applicationEnd: new Date("2026-04-30"),
    field: ["AI", "디자인", "영상/미디어"],
    target: ["청년(만39세 이하)", "대학생"],
    region: "서울",
    summary:
      "NEXT 서초, AI로 미래를 디자인하다. 19세~39세 청년 대상 AI 활용 이미지·영상 작품 공모. 총 20개 작품 시상, 시상금 총 1,280만원.",
    prize:
      "총 1,280만원 (대상 200만원, 최우수상 100만원, 우수상 2명 각 70만원, 장려상 7명 각 50만원)",
    eligibility: "접수 마감일 기준 만 19세~39세 청년, 개인 또는 3인 이내 팀",
    applyUrl: "http://aiseocho.gcontest.co.kr",
    sourceUrl: "https://thinkyou.co.kr/mobile/contest/61354/",
    checklist: [
      "작품 파일(이미지 또는 영상)",
      "작품 설명서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 대학생 PR-Competition 내정보지킴이 캠페인",
    category: "contest",
    organizer: "한국광고홍보학회",
    applicationStart: new Date("2026-03-23"),
    applicationEnd: new Date("2026-04-30"),
    field: ["마케팅", "광고", "기획/아이디어"],
    target: ["대학생", "대학원생"],
    region: "서울",
    summary:
      "개인정보보호를 주제로 한 PR 캠페인 아이디어를 제안하는 대학생 경연대회. 광고·홍보 관련 학과 재학생 대상, 2~3인 팀 단위 참여.",
    prize: "총 200만원 (대상 100만원, 금상 50만원, 은상 30만원, 동상 20만원)",
    eligibility:
      "광고·홍보 및 유관 학과 전공 대학생 1학년 이상 재학생 (2~3인 팀)",
    applyUrl: "https://kadpr.or.kr",
    sourceUrl: "https://www.contestalgo.com/sub/contest_view.php?num=8788",
    checklist: ["PDF 제안서(20~30장)", "개인정보 수집·이용 동의서"],
    isActive: true,
  },
  {
    title: "2026 지식재산 모두의 아이디어 공모전",
    category: "contest",
    organizer: "지식재산처",
    applicationStart: new Date("2026-01-08"),
    applicationEnd: new Date("2026-04-15"),
    field: ["기획/아이디어", "AI", "사회혁신"],
    target: ["대학생", "대학원생", "일반인"],
    region: "전국",
    summary:
      "정부·기업 과제 해결 아이디어(지정공모) 및 주제 제한 없는 자유공모 두 트랙 운영. 총 상금 7.8억원, 1만 명 포상 규모의 대형 공모전.",
    prize:
      "총 7.8억원 (왕중왕전 1등 1억원, 금상 20점 각 1,000만원, 참여상 1만점 각 3만원)",
    eligibility: "아이디어를 보유한 대한민국 국민 누구나",
    applyUrl: "https://www.ipidea.or.kr",
    sourceUrl:
      "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=031410001&str_no=202601080034",
    checklist: ["아이디어 제안서", "개인정보 수집·이용 동의서"],
    isActive: true,
  },
  {
    title: "2026 공공데이터 활용 창작 공모전",
    category: "contest",
    organizer: "행정안전부",
    applicationStart: new Date("2026-03-10"),
    applicationEnd: new Date("2026-05-09"),
    field: ["데이터", "AI", "소프트웨어"],
    target: ["대학생", "일반인"],
    region: "전국",
    summary:
      "공공데이터포털의 데이터를 활용하여 사회 문제를 해결하는 서비스·앱·시각화 작품을 공모합니다. 최대 5인 팀 참가 가능.",
    prize: "총 5,000만원 (대상 1,500만원)",
    eligibility: "대한민국 국민 누구나 (팀 최대 5인)",
    applyUrl: "https://www.data.go.kr/suc/preliminaryRound.do",
    sourceUrl: "https://www.data.go.kr/suc/preliminaryRound.do",
    checklist: [
      "참가신청서",
      "작품설명서(A4 5매 이내)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 K-디자인 어워드 학생 부문",
    category: "contest",
    organizer: "한국디자인진흥원(KIDP)",
    applicationStart: new Date("2026-03-15"),
    applicationEnd: new Date("2026-06-14"),
    field: ["디자인", "UX/UI", "제품디자인"],
    target: ["대학생", "대학원생"],
    region: "전국",
    summary:
      "국내 대학(원)생을 대상으로 한 디자인 역량 발굴 공모전. 시각·제품·공간·UX 4개 트랙 운영. 총 상금 2,500만원.",
    prize: "총 2,500만원 (각 트랙 대상 300만원)",
    eligibility: "국내 4년제 또는 전문대학 재학·휴학생",
    applyUrl: "https://www.kidp.or.kr",
    sourceUrl: "https://www.kidp.or.kr",
    checklist: [
      "작품 포트폴리오(PDF)",
      "재학증명서",
      "지도교수 확인서(선택)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "부산 스마트시티 아이디어 공모전 2026",
    category: "contest",
    organizer: "부산광역시·부산테크노파크",
    applicationStart: new Date("2026-04-15"),
    applicationEnd: new Date("2026-07-14"),
    field: ["스마트시티", "IoT", "환경"],
    target: ["대학생", "일반인", "스타트업"],
    region: "부산",
    summary:
      "부산의 도시 문제를 ICT 기술로 해결하는 아이디어 공모. 교통·환경·안전·생활편의 분야 중심.",
    prize: "총 3,500만원 (최우수 1,000만원)",
    eligibility: "부산시민 또는 부산 소재 기업·대학 구성원",
    applyUrl: "https://www.btp.or.kr",
    sourceUrl: "https://www.btp.or.kr",
    checklist: [
      "아이디어 기획서(10매 이내)",
      "시연 영상(3분 이내)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "제8회 핀테크 아이디어 공모전",
    category: "contest",
    organizer: "금융위원회·코스콤",
    applicationStart: new Date("2026-06-01"),
    applicationEnd: new Date("2026-07-31"),
    field: ["핀테크", "금융", "AI"],
    target: ["대학생", "대학원생", "일반인"],
    region: "전국",
    summary:
      "금융 서비스 혁신을 위한 핀테크 아이디어를 공모합니다. 실현 가능성과 비즈니스 모델 구체성 중점 평가.",
    prize: "총 6,000만원 (대상 2,000만원)",
    eligibility: "대한민국 국민 누구나 (팀 최대 4인)",
    applyUrl: "https://fintech.or.kr",
    sourceUrl: "https://linkareer.com/activity/257488",
    checklist: [
      "사업계획서",
      "프로토타입 또는 목업",
      "팀 소개서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 삼성전자 대학생 소프트웨어 공모전",
    category: "contest",
    organizer: "삼성전자",
    applicationStart: new Date("2026-07-15"),
    applicationEnd: new Date("2026-08-14"),
    field: ["AI", "소프트웨어", "IoT"],
    target: ["대학생", "대학원생"],
    region: "전국",
    summary:
      "홈·모바일·오피스 등 디지털 신상품 및 콘텐츠·서비스·솔루션 관련 신규 비즈니스 아이디어를 공모합니다. 수상자는 삼성전자 입사 지원 시 가산점 부여.",
    prize:
      "총 1,500만원 (대상 500만원, 최우수상 300만원, 우수상 2팀 각 200만원)",
    eligibility: "국내외 대학교·대학원 재학생 (휴학생 포함, 3인 이하 팀)",
    applyUrl: "https://www.samsung.com/sec",
    sourceUrl: "https://news.samsung.com/kr",
    checklist: [
      "아이디어 제안서",
      "재학증명서",
      "팀 구성원 동의서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2025 환경데이터 활용 및 분석 공모전",
    category: "contest",
    organizer: "환경부·한국환경산업기술원",
    applicationStart: new Date("2025-04-07"),
    applicationEnd: new Date("2025-05-19"),
    field: ["환경", "사회혁신", "AI"],
    target: ["대학생", "대학원생", "일반인"],
    region: "전국",
    summary:
      "탄소중립 및 친환경 생활 실천을 위한 혁신 아이디어 공모. 에너지 절감, 자원순환, 친환경 교통 분야 우선.",
    prize: "총 3,000만원 (대상 700만원)",
    eligibility: "대한민국 국민 누구나 (개인 또는 팀 최대 4인)",
    applyUrl: "https://www.keiti.re.kr",
    sourceUrl: "https://career.kau.ac.kr/ko/community/notice2/view/16102",
    checklist: [
      "아이디어 제안서",
      "기대효과 설명서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },

  // ─────────────────────────────────────────
  // hackathon (해커톤) × 10
  // ─────────────────────────────────────────
  {
    title: "2026 블록체인&AI 해커톤 (한국디지털인증협회)",
    category: "hackathon",
    organizer: "한국디지털인증협회·행정안전부",
    applicationStart: new Date("2026-05-01"),
    applicationEnd: new Date("2026-09-30"),
    field: ["AI", "블록체인", "모바일"],
    target: ["대학생", "대학원생", "일반인", "스타트업"],
    region: "서울",
    summary:
      "모바일 신분증을 활용한 블록체인·AI 기반 창의적 서비스 아이디어 해커톤. 입상팀에 창업 지원금 최대 10억원, 총 상금 3,000만원. 결선은 페어몬트 앰배서더 서울에서 개최.",
    prize: "총 상금 3,000만원 (대상 1,500만원) + 창업 지원금 최대 10억원",
    eligibility: "만 18세 이상 최대 5인 팀 (설립 5년 이내 스타트업 또는 개인)",
    applyUrl: "https://opendid.org/hackathon/2026/",
    sourceUrl: "https://opendid.org/hackathon/2026/",
    checklist: [
      "팀 등록서",
      "서비스 아이디어 기획서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "Fast Builderthon 2026: 패스트캠퍼스 AI 해커톤",
    category: "hackathon",
    organizer: "패스트캠퍼스",
    applicationStart: new Date("2026-02-01"),
    applicationEnd: new Date("2026-04-30"),
    field: ["AI", "소프트웨어", "개발"],
    target: ["대학생", "개발자", "기획자"],
    region: "서울",
    summary:
      "AI 시대 새로운 창작 방식의 정점에 도전하는 해커톤. 총 시상 규모 1억 3,900만원 상당. AI를 활용한 서비스 개발 및 비즈니스 모델 구현.",
    prize: "총 1억 3,900만원 상당",
    eligibility: "누구나 (팀 단위 참가)",
    applyUrl: "https://fastcampus.co.kr/builderthon2026",
    sourceUrl: "https://fastcampus.co.kr/builderthon2026",
    checklist: ["사전 등록서", "아이디어 요약서", "개인정보 수집·이용 동의서"],
    isActive: true,
  },
  {
    title: "KISTI Open Hackathon 2026 (AI/HPC)",
    category: "hackathon",
    organizer: "KISTI·HPE·NVIDIA·OpenACC Organization",
    applicationStart: new Date("2025-12-05"),
    applicationEnd: new Date("2026-04-30"),
    field: ["AI", "HPC", "소프트웨어"],
    target: ["대학원생", "연구자", "개발자"],
    region: "대전",
    summary:
      "NVIDIA GH200 슈퍼칩 탑재 KISTI 슈퍼컴퓨터 6호기 '한강'을 활용해 AI/HPC 애플리케이션 성능을 극대화하는 해커톤. 전문가 멘토링 포함.",
    prize: "멘토링 참여 기회 + KISTI 연구 협력 연계",
    eligibility: "연구자·개발자 누구나 (팀 당 3인 내외, 최대 4인)",
    applyUrl: "https://www.openhackathons.org/s/upcoming-events",
    sourceUrl: "https://www.kisti.re.kr/notifications/post/notice/6841",
    checklist: [
      "팀 신청서 (openhackathons.org)",
      "코드/프로젝트 설명서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "매경미디어×앤스로픽 'News to Action' AI 해커톤",
    category: "hackathon",
    organizer: "매일경제미디어그룹·Anthropic",
    applicationStart: new Date("2026-01-01"),
    applicationEnd: new Date("2026-03-20"),
    field: ["AI", "미디어", "소프트웨어"],
    target: ["대학생", "취업준비생", "직장인", "일반인"],
    region: "서울",
    summary:
      "매일경제 60년 축적 뉴스 데이터와 Anthropic Claude API를 결합해 사회적 가치를 창출하는 서비스를 개발하는 당일 해커톤 (2026.3.20 종료). Claude API 크레딧 현장 지원.",
    prize: "대상 200만원 + 매경 인턴십 기회, 앤스로픽 Claude API 전폭 지원",
    eligibility:
      "뉴스 데이터와 AI 활용 서비스 개발에 관심 있는 누구나 — 대학생, 취업준비생, 직장인 등 제한 없음 (개인 또는 최대 4인 팀)",
    applyUrl:
      "https://docs.google.com/forms/d/e/1FAIpQLSenXRHKVWd2WfDqecVNVTH7uWD0VJkynknE0GRSTXFpkDau_A/viewform",
    sourceUrl: "https://n.news.naver.com/mnews/article/009/0005617474?sid=102",
    checklist: [
      "참가 신청서",
      "개인정보 동의서",
      "개발 계획서(자유 양식)",
      "개인 노트북 지참",
    ],
    isActive: true,
  },
  {
    title: "Snowflake 해커톤 2026 Korea",
    category: "hackathon",
    organizer: "Snowflake Korea",
    applicationStart: new Date("2026-03-17"),
    applicationEnd: new Date("2026-04-29"),
    field: ["AI", "데이터", "소프트웨어"],
    target: ["개발자", "대학생", "스타트업"],
    region: "서울",
    summary:
      "누구나 만들 수 있는 나만의 AI 에이전트! 데이터와 AI로 나만의 앱을 만드는 해커톤. 비즈니스 트랙·테크 트랙 운영. 결선은 강남 레드버튼 컬쳐스테이지에서 개최.",
    prize: "상금 및 Snowflake 크레딧 (각 트랙 TOP 3 시상)",
    eligibility: "누구나 (팀 단위)",
    applyUrl: "https://www.snowflake.com/snowflake-hackathon-2026-korea/",
    sourceUrl: "https://www.snowflake.com/snowflake-hackathon-2026-korea/",
    checklist: [
      "해커톤 참가 신청서",
      "아이디어 요약",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2025 환경창업대전 (Eco+ Start-Up Challenge)",
    category: "hackathon",
    organizer: "환경부·한국환경산업기술원",
    applicationStart: new Date("2025-04-01"),
    applicationEnd: new Date("2025-05-02"),
    field: ["환경", "에너지", "창업"],
    target: ["대학생", "스타트업", "개발자"],
    region: "전국",
    summary:
      "탄소중립 달성을 위한 기술 솔루션을 개발하는 온라인 해커톤. 에너지 절감·탄소추적·친환경 모빌리티 트랙 운영.",
    prize: "총 3,500만원 (각 트랙 우승 500만원)",
    eligibility: "국내외 참가 가능 (팀 2~5인)",
    applyUrl: "https://ecosq.or.kr",
    sourceUrl:
      "https://www.keiti.re.kr/site/keiti/ex/board/View.do?cbIdx=277&bcIdx=38446",
    checklist: [
      "팀 등록서",
      "트랙 선택 및 아이디어 개요",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2025 서울 열린데이터광장 공공데이터 활용 창업경진대회",
    category: "hackathon",
    organizer: "서울특별시",
    applicationStart: new Date("2025-03-05"),
    applicationEnd: new Date("2025-05-09"),
    field: ["데이터", "스마트시티", "공공서비스"],
    target: ["대학생", "개발자", "일반인"],
    region: "서울",
    summary:
      "서울 열린데이터광장 공개 데이터를 활용해 시민 생활 편의를 높이는 앱·서비스를 24시간 안에 개발하는 해커톤.",
    prize: "총 3,000만원 (1등 1,000만원)",
    eligibility: "누구나 (팀 2~4인)",
    applyUrl: "https://data.seoul.go.kr",
    sourceUrl: "https://www.allforyoung.com/posts/61743",
    checklist: [
      "사전 등록서",
      "프로젝트 아이디어 요약(300자)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },

  // ─────────────────────────────────────────
  // startup (예창패 / 창업 프로그램) × 10
  // ─────────────────────────────────────────
  {
    title: "2026년 예비창업패키지 예비창업자 모집",
    category: "startup",
    organizer: "중소벤처기업부·창업진흥원",
    applicationStart: new Date("2026-03-06"),
    applicationEnd: new Date("2026-03-24"),
    field: ["창업", "전 분야"],
    target: ["예비창업자"],
    region: "전국",
    summary:
      "혁신적인 기술과 사업모델을 보유한 예비창업자를 발굴·지원. 평균 4,000만원, 최대 8,000만원 사업화 자금 지원. K-Startup 온라인 신청.",
    prize: "평균 4,000만원, 최대 8,000만원 (사업화 자금)",
    eligibility: "사업자등록증을 보유하지 않은 예비창업자 (공고일 기준)",
    applyUrl: "https://www.k-startup.go.kr",
    sourceUrl: "https://www.venturesquare.net/announcement/1041449",
    checklist: ["사업계획서", "기타 제출서류", "개인정보 수집·이용 동의서"],
    isActive: true,
  },
  {
    title: "2026년 초기창업패키지(일반형) 창업기업 모집",
    category: "startup",
    organizer: "중소벤처기업부·창업진흥원",
    applicationStart: new Date("2026-01-23"),
    applicationEnd: new Date("2026-04-30"),
    field: ["창업", "전 분야"],
    target: ["스타트업"],
    region: "전국",
    summary:
      "유망 창업 아이템·기술을 보유한 창업 3년 이내 초기창업기업 지원. 평균 5,000만원, 최대 1억원 사업화 자금 지원. 주관기관별 특화 분야 창업프로그램 포함.",
    prize: "평균 5,000만원, 최대 1억원 (사업화 자금)",
    eligibility: "창업 후 3년 이내 초기창업기업 (법인 또는 개인사업자)",
    applyUrl: "https://www.k-startup.go.kr",
    sourceUrl:
      "https://www.mss.go.kr/site/smba/ex/bbs/View.do?cbIdx=310&bcIdx=1065015",
    checklist: [
      "사업계획서",
      "사업자등록증",
      "신분 확인 서류",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "초기창업패키지 2026 딥테크 트랙",
    category: "startup",
    organizer: "중소벤처기업부·창업진흥원",
    applicationStart: new Date("2026-03-01"),
    applicationEnd: new Date("2026-05-31"),
    field: ["딥테크", "AI", "바이오"],
    target: ["스타트업"],
    region: "전국",
    summary:
      "딥테크 분야 초기 스타트업의 기술 사업화를 지원. 딥테크 최대 1.5억원 지원 및 전문 보육 기관 연계. 일반형 대비 더 큰 지원 규모.",
    prize: "최대 1.5억원 (딥테크 트랙)",
    eligibility: "창업 후 3년 이내 딥테크 분야 초기창업기업",
    applyUrl: "https://www.k-startup.go.kr",
    sourceUrl: "https://www.kised.or.kr/menu.es?mid=a10205020000",
    checklist: [
      "사업계획서",
      "사업자등록증",
      "기술 관련 증빙자료",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "TIPS 프로그램 2026 상반기 모집",
    category: "startup",
    organizer: "중소벤처기업부·민간 투자사",
    applicationStart: new Date("2026-03-10"),
    applicationEnd: new Date("2026-05-31"),
    field: ["딥테크", "AI", "바이오", "소프트웨어"],
    target: ["스타트업"],
    region: "전국",
    summary:
      "민간 투자사 추천을 통해 선발된 스타트업에 정부 R&D 자금 최대 5억원을 지원하는 엔젤투자 매칭 프로그램. TIPS 운영사 추천 필수.",
    prize: "R&D 자금 최대 5억원 + 해외마케팅·창업사업화 추가 지원",
    eligibility: "창업 7년 이내 기술창업기업 (TIPS 운영사 추천 필수)",
    applyUrl: "https://www.k-startup.go.kr",
    sourceUrl: "https://www.k-startup.go.kr",
    checklist: [
      "사업계획서",
      "투자사 추천서",
      "사업자등록증",
      "기술개발 계획서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "서울창업허브 글로벌 액셀러레이팅 2026",
    category: "startup",
    organizer: "서울경제진흥원(SBA)",
    applicationStart: new Date("2026-04-01"),
    applicationEnd: new Date("2026-05-31"),
    field: ["글로벌 진출", "AI", "SaaS"],
    target: ["스타트업"],
    region: "서울",
    summary:
      "해외 진출을 목표로 하는 서울 소재 스타트업을 선발해 글로벌 멘토링·IR·마케팅비 최대 3,000만원 지원.",
    prize: "사업화 지원금 최대 3,000만원 + 글로벌 PoC 연계",
    eligibility: "서울 소재 또는 서울 이전 예정 창업 5년 이내 스타트업",
    applyUrl: "https://sba.seoul.kr",
    sourceUrl: "https://sba.seoul.kr",
    checklist: [
      "사업계획서(영문 포함)",
      "사업자등록증",
      "서비스/제품 소개 자료",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "여성창업 패키지 2026",
    category: "startup",
    organizer: "중소벤처기업부·여성기업종합지원센터",
    applicationStart: new Date("2026-05-01"),
    applicationEnd: new Date("2026-06-30"),
    field: ["창업", "소셜벤처"],
    target: ["예비창업자"],
    region: "전국",
    summary:
      "여성 창업자를 위한 전용 창업 지원 프로그램. 사업화 자금 최대 7,000만원 및 맞춤형 멘토링 제공.",
    prize: "최대 7,000만원",
    eligibility: "여성 예비창업자 및 창업 3년 이내 여성 대표 기업",
    applyUrl: "https://www.wbiz.or.kr",
    sourceUrl: "https://www.wbiz.or.kr",
    checklist: [
      "사업계획서",
      "대표자 신분증(여성 확인)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 청년창업사관학교 입교생 모집",
    category: "startup",
    organizer: "중소벤처기업부·중소기업진흥공단",
    applicationStart: new Date("2026-04-01"),
    applicationEnd: new Date("2026-05-15"),
    field: ["창업", "전 분야", "AI"],
    target: ["예비창업자", "청년(만39세 이하)"],
    region: "전국",
    summary:
      "만 39세 이하 청년 예비창업자를 대상으로 창업 교육·공간·자금을 원스톱 지원하는 청년창업사관학교. 최대 1억원 사업화 지원.",
    prize: "최대 1억원 사업화 자금 + 창업 공간·멘토링 무상 제공",
    eligibility: "만 39세 이하 예비창업자 (공고일 기준 사업자등록 전)",
    applyUrl: "https://www.sbc.or.kr",
    sourceUrl: "https://www.sbc.or.kr",
    checklist: [
      "사업계획서",
      "대표자 신분증",
      "청년 연령 증빙서류",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "대학창업펀드 2026 (학생 창업)",
    category: "startup",
    organizer: "교육부·한국연구재단",
    applicationStart: new Date("2026-06-15"),
    applicationEnd: new Date("2026-07-31"),
    field: ["창업", "기술사업화", "AI"],
    target: ["대학생", "대학원생"],
    region: "전국",
    summary:
      "대학 재학(원)생의 창업 도전을 지원하는 학생 창업 특화 프로그램. 사업화 자금 최대 5,000만원 지원.",
    prize: "최대 5,000만원",
    eligibility: "대학(원) 재학생 또는 졸업 3년 이내 (팀원 과반 이상 재학생)",
    applyUrl: "https://www.nrf.re.kr",
    sourceUrl: "https://www.nrf.re.kr",
    checklist: [
      "사업계획서",
      "재학증명서 또는 졸업증명서",
      "사업자등록증(해당 시)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2025 소셜벤처 혁신경연대회 (제9회)",
    category: "startup",
    organizer: "고용노동부·한국사회적기업진흥원",
    applicationStart: new Date("2025-07-16"),
    applicationEnd: new Date("2025-07-31"),
    field: ["사회혁신", "창업", "소셜벤처"],
    target: ["예비창업자", "대학생", "청년(만39세 이하)"],
    region: "전국",
    summary:
      "사회문제 해결을 위한 소셜벤처 아이디어를 발굴하는 창업경진대회. 우수 팀에게 사업화 자금 및 사회적기업 인증 연계 지원.",
    prize: "최대 5,000만원 (사업화 자금) + 사회적기업 인증 우선 연계",
    eligibility: "사업자등록 전 예비창업자 또는 창업 1년 이내 소셜벤처",
    applyUrl: "https://yse.or.kr/notice_outside/?bmode=view&idx=166865356",
    sourceUrl: "https://yse.or.kr/notice_outside/?bmode=view&idx=166865356",
    checklist: [
      "사업계획서",
      "사회적 가치 실현 방안",
      "팀 구성원 소개서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 네이버 D2SF 스타트업 지원 프로그램",
    category: "startup",
    organizer: "네이버 D2 스타트업 팩토리",
    applicationStart: new Date("2026-05-01"),
    applicationEnd: new Date("2026-06-30"),
    field: ["AI", "딥테크", "소프트웨어", "개발"],
    target: ["스타트업", "예비창업자"],
    region: "경기",
    summary:
      "기술 중심 초기 스타트업을 위한 네이버의 투자·지원 프로그램. 시드 투자 및 네이버 기술·인프라 연계 지원.",
    prize: "시드 투자 + 네이버 클라우드·API 크레딧 + 멘토링",
    eligibility: "기술 중심 창업 3년 이내 스타트업 (아이디어 단계도 가능)",
    applyUrl: "https://d2startup.com",
    sourceUrl: "https://d2startup.com",
    checklist: [
      "사업계획서",
      "기술 데모 또는 프로토타입",
      "팀 소개서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },

  // ─────────────────────────────────────────
  // grant (지원금 / 보조금) × 10
  // ─────────────────────────────────────────
  {
    title: "2026 청년내일저축계좌 신청",
    category: "grant",
    organizer: "보건복지부",
    applicationStart: new Date("2026-05-04"),
    applicationEnd: new Date("2026-05-20"),
    field: ["일자리", "자산형성"],
    target: ["청년(만39세 이하)"],
    region: "전국",
    summary:
      "저소득 근로 청년을 위한 자산형성 지원사업. 매월 본인 10만원 저축 시 정부가 30만원 매칭 지원. 3년 만기 시 최대 1,440만원+이자 수령 가능.",
    prize: "월 30만원 정부 매칭 (3년 만기 시 최대 1,440만원+이자)",
    eligibility:
      "만 15~39세 근로 청년 (기준 중위소득 50% 이하 가구, 차상위 이하)",
    applyUrl: "https://www.bokjiro.go.kr",
    sourceUrl: "https://young.busan.go.kr/index.nm?menuCd=48",
    checklist: [
      "사회복지서비스 신청서",
      "자산형성지원사업 참여 신청서",
      "자가진단표",
      "가족관계증명서",
      "소득증빙자료",
      "개인정보 수집·이용·제공 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 청년미래적금 (청년도약계좌 후속 상품)",
    category: "grant",
    organizer: "금융위원회·서민금융진흥원",
    applicationStart: new Date("2026-06-01"),
    applicationEnd: new Date("2026-08-31"),
    field: ["자산형성", "금융"],
    target: ["청년(만39세 이하)"],
    region: "전국",
    summary:
      "2026년 6월 출시 예정인 청년 전용 정책 금융상품. 월 50만원 한도 저축 시 정부가 최대 12% 매칭. 3년 만기 시 최대 2,200만원 수령.",
    prize: "정부 매칭 최대 12% (3년 만기 시 최대 2,200만원)",
    eligibility:
      "만 19~34세 청년 (연소득 6,000만원 이하 일반형, 3,600만원 이하 우대형)",
    applyUrl: "https://www.kinfa.or.kr",
    sourceUrl: "https://job.gg.go.kr/thema/exprcDtl.do?seq=6017",
    checklist: [
      "은행 앱 비대면 신청",
      "소득 및 가구원 정보 확인 동의",
      "주민등록증 또는 운전면허증",
    ],
    isActive: true,
  },
  {
    title: "2026 청년일자리도약장려금",
    category: "grant",
    organizer: "고용노동부",
    applicationStart: new Date("2026-01-01"),
    applicationEnd: new Date("2026-09-30"),
    field: ["일자리", "취업"],
    target: ["청년(만39세 이하)"],
    region: "전국",
    summary:
      "비수도권 중소기업에 정규직 취업한 청년에게 최대 720만원 지원. 2026년부터 비수도권 전체 중소기업으로 대상 확대. 상시 신청 가능.",
    prize: "최대 720만원 (2년간 근속 시, 지역별 차등 지원)",
    eligibility:
      "만 15~34세 청년, 비수도권 우선지원대상 기업 정규직 채용 후 6개월 이상 고용유지",
    applyUrl: "https://www.work24.go.kr",
    sourceUrl:
      "https://m.work24.go.kr/cm/c/f/1100/selecSystInfo.do?systId=SI00000318",
    checklist: [
      "취업 확인서 (기업 신청 후 청년 동의)",
      "고용보험 가입 확인",
      "주민등록증",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "국민취업지원제도 참여 신청",
    category: "grant",
    organizer: "고용노동부",
    applicationStart: new Date("2026-01-01"),
    applicationEnd: new Date("2026-12-31"),
    field: ["일자리", "취업"],
    target: ["청년(만39세 이하)", "일반인"],
    region: "전국",
    summary:
      "취업을 원하는 국민에게 1:1 상담·직업훈련·일경험 등을 제공하고 구직촉진수당을 지급하는 제도. 고용보험 미가입자도 참여 가능.",
    prize: "구직촉진수당 월 50만원 × 최대 6개월 (1유형 저소득층)",
    eligibility: "만 15~69세, 가구소득 중위소득 60% 이하 (청년은 120% 이하)",
    applyUrl: "https://www.work24.go.kr",
    sourceUrl:
      "https://www.work24.go.kr/cm/c/f/1100/selecSystInfo.do?systId=SI00000316",
    checklist: [
      "취업지원 신청서",
      "개인정보 등 수집·이용·제공 동의서",
      "소득·재산 확인 서류",
      "주민등록등본",
    ],
    isActive: true,
  },
  {
    title: "중소기업 AI 도입 바우처 2026",
    category: "grant",
    organizer: "중소벤처기업부·중소기업기술정보진흥원",
    applicationStart: new Date("2026-03-03"),
    applicationEnd: new Date("2026-05-31"),
    field: ["AI", "디지털전환", "제조"],
    target: ["스타트업"],
    region: "전국",
    summary:
      "AI 솔루션 도입을 원하는 중소기업에 최대 3,000만원(자부담 30%) 바우처 지원. 수요기업-공급기업 매칭 방식.",
    prize: "최대 3,000만원 (자부담 30%)",
    eligibility: "중소기업기본법상 중소기업 (제조·서비스업)",
    applyUrl: "https://www.smtech.go.kr",
    sourceUrl: "https://www.smtech.go.kr",
    checklist: [
      "사업계획서",
      "사업자등록증",
      "재무제표(최근 1년)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "청년 디지털 창작자 지원사업 2026",
    category: "grant",
    organizer: "문화체육관광부·한국콘텐츠진흥원",
    applicationStart: new Date("2026-04-07"),
    applicationEnd: new Date("2026-05-23"),
    field: ["콘텐츠", "영상/미디어"],
    target: ["청년(만39세 이하)"],
    region: "전국",
    summary:
      "유튜브·웹툰·팟캐스트 등 디지털 콘텐츠를 제작하는 청년 창작자에게 제작비·장비비 최대 500만원 지원.",
    prize: "최대 500만원 (제작비·장비비)",
    eligibility: "만 19~39세 청년, 채널 구독자 1,000명 이상(또는 동등 실적)",
    applyUrl: "https://www.kocca.kr",
    sourceUrl: "https://www.kocca.kr",
    checklist: [
      "활동 포트폴리오",
      "지원금 사용 계획서",
      "채널 현황 캡처",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "소상공인 스마트상점 기술보급 사업 2026",
    category: "grant",
    organizer: "중소벤처기업부·소상공인시장진흥공단",
    applicationStart: new Date("2026-04-20"),
    applicationEnd: new Date("2026-06-06"),
    field: ["스마트기술", "소상공인"],
    target: ["일반인"],
    region: "전국",
    summary:
      "키오스크·서빙로봇·스마트POS 등 스마트 기술을 소상공인 점포에 도입하는 비용의 70~80%를 보조.",
    prize: "최대 2,000만원 (자부담 20~30%)",
    eligibility: "소상공인기본법상 소상공인 (사업자등록 후 6개월 이상)",
    applyUrl: "https://www.semas.or.kr",
    sourceUrl: "https://www.semas.or.kr",
    checklist: [
      "사업자등록증",
      "최근 부가세 과세표준 증명",
      "도입기술 견적서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "K-스타트업 글로벌 마케팅 지원사업 2026",
    category: "grant",
    organizer: "KOTRA·중소벤처기업부",
    applicationStart: new Date("2026-05-12"),
    applicationEnd: new Date("2026-06-27"),
    field: ["글로벌 진출", "마케팅"],
    target: ["스타트업"],
    region: "전국",
    summary:
      "해외 전시회 참가·현지 마케팅·바이어 발굴 비용을 지원하여 스타트업의 글로벌 진출을 가속화하는 사업.",
    prize: "최대 5,000만원 (해외 마케팅비 70% 매칭)",
    eligibility: "수출 실적 보유 또는 수출 의지가 있는 창업 7년 이내 기업",
    applyUrl: "https://www.kotra.or.kr",
    sourceUrl: "https://www.kotra.or.kr",
    checklist: [
      "사업계획서(글로벌 전략 포함)",
      "사업자등록증",
      "수출 실적 증빙(해당 시)",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "지역주도형 청년 일자리 사업 2026",
    category: "grant",
    organizer: "행정안전부·각 광역지자체",
    applicationStart: new Date("2026-06-02"),
    applicationEnd: new Date("2026-07-31"),
    field: ["일자리", "취업"],
    target: ["청년(만39세 이하)"],
    region: "전국",
    summary:
      "비수도권 지역 기업·기관에 취업하거나 창업하는 청년에게 인건비·정착비 최대 2년간 지원.",
    prize: "월 최대 180만원 × 최대 24개월",
    eligibility: "만 18~39세 청년, 비수도권 지역 사업체 취·창업",
    applyUrl: "https://www.mois.go.kr",
    sourceUrl: "https://www.mois.go.kr",
    checklist: [
      "취업(창업) 확인서",
      "주민등록등본",
      "청년 연령 증빙",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
  {
    title: "2026 R&D 바우처 (중견기업 혁신형)",
    category: "grant",
    organizer: "산업통상자원부·한국산업기술진흥원(KIAT)",
    applicationStart: new Date("2026-07-01"),
    applicationEnd: new Date("2026-08-29"),
    field: ["R&D", "제조혁신", "AI"],
    target: ["스타트업"],
    region: "전국",
    summary:
      "혁신 역량을 갖춘 중견기업이 연구기관·대학과 공동 R&D를 수행할 수 있도록 바우처 형태로 최대 2억원 지원.",
    prize: "최대 2억원 (자부담 40%)",
    eligibility: "중견기업법상 중견기업 또는 강소기업 인증 보유 기업",
    applyUrl: "https://www.kiat.or.kr",
    sourceUrl: "https://www.kiat.or.kr",
    checklist: [
      "사업계획서",
      "사업자등록증",
      "재무제표(최근 2년)",
      "R&D 과제 계획서",
      "개인정보 수집·이용 동의서",
    ],
    isActive: true,
  },
];
